### ISSUE TITLE
Doesn't work on ios 12

### ISSUE THREAD

**Issue by ghost** [XMB5/trolldrop#1]
@XMB5 I have done everything as stated in the readme file and it still doesn't detect any people to airdrop to is there any solution or could you fix this? I have tested this on two devices iPod touch and iPhone 6 to no avail I have also tried it without loading tweaks to see if there was any interference.

**Comment by tombaki** [comment]
@DJCHICKEN4 it's use private api and it's changed every version.

**Comment by ghost** [comment]
@tombaki I found this which was released by another developer and it works and has a gui https://www.reddit.com/r/jailbreak/comments/bihu9i/release_trolldrop_app_no_longer_a_piece_of_crap/
